name: Release

on:
  push:
    tags:
      - '*'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23rc2'

      - name: Install zip
        run: sudo apt-get install zip

      - name: Build binaries
        run: make release

      - name: Archive binaries
        run: |
          mkdir -p release
          mv bin/*.tgz release/
          mv bin/*.zip release/
      - name: Get version from VERSION file
        id: get_version
        run: |
          VERSION=$(cat VERSION)
          echo "::set-output name=VERSION::$VERSION"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: "Release ${{ steps.get_version.outputs.VERSION }}"
          draft: false
          prerelease: false

      - name: Upload Linux and macOS Binaries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in release/*.tgz; do
            curl -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: application/gzip" \
              --data-binary @$file \
              "${{ steps.create_release.outputs.upload_url }}?name=$(basename $file)"
          done

      - name: Upload Windows Binaries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in release/*.zip; do
            curl -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: application/zip" \
              --data-binary @$file \
              "${{ steps.create_release.outputs.upload_url }}?name=$(basename $file)"
          done